#!/usr/bin/env python3
"""
AI Dev Journal - Chart Workbook Generator

Reads the Excel workbook generated by report.py, leaves that input file unchanged,
and writes a new enriched workbook containing the original report sheets plus
visual chart/data sheets.

Usage:
    python plot_charts.py report.xlsx -o report_with_charts.xlsx
    python plot_charts.py report.xlsx --model gpt-5.4-mini
    python plot_charts.py report.xlsx --no-ai

OpenAI-compatible model configuration matches report.py:
    OPENAI_BASE_URL=https://...
    OPENAI_API_KEY=...
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import requests
from openpyxl import load_workbook
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.formatting.rule import ColorScaleRule
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

try:
    from dotenv import load_dotenv

    load_dotenv()
except Exception:
    # dotenv is a convenience only; environment variables still work without it.
    pass


# --------------------------------------------------------------------------- #
# Constants
# --------------------------------------------------------------------------- #

OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

RAW_LOG_SHEET = "📝 Raw Log"
AI_COMPARE_SHEET = "🤖 AI Lesson Compare"

EFFICIENCY_SHEET = "📈 Efficiency Charts"
RATING_SHEET = "⭐ Rating Charts"
ERROR_DATA_SHEET = "🏷️ Prompt Error Data"
ERROR_CHART_SHEET = "🏷️ Error Charts"
SDLC_SHEET = "🧭 SDLC Summary"

GENERATED_SHEETS = [
    SDLC_SHEET,
    EFFICIENCY_SHEET,
    RATING_SHEET,
    ERROR_DATA_SHEET,
    ERROR_CHART_SHEET,
    "🧭 SDLC Data",  # legacy name from earlier versions of this script
]

CACHE_PATH = Path(".ai_chart_cache.json")
PROMPT_VERSION = "chart-classifier-v1"

MAX_ERROR_LABELS_FOR_CHART = 10
MAX_LABELS_PER_SESSION = 3

ERROR_TAXONOMY: dict[str, str] = {
    "Clear and Format": (
        "Prompt thiếu yêu cầu rõ ràng, thiếu format/schema đầu ra, hoặc thiếu "
        "các bước tuần tự/ràng buộc cụ thể."
    ),
    "Missing Context": (
        "Prompt thiếu bối cảnh nghiệp vụ, stack công nghệ, dữ liệu nền, mục tiêu, "
        "hoặc người dùng cuối."
    ),
    "Missing Examples": (
        "Task lặp lại/phức tạp nhưng prompt thiếu ví dụ few-shot hoặc ví dụ không đủ đa dạng."
    ),
    "Weak Structure": (
        "Prompt trộn lẫn instruction, context, input, output hoặc thiếu cấu trúc rõ như XML tags."
    ),
    "No Role": "Prompt không gán vai trò/persona chuyên môn phù hợp cho AI.",
    "Negative Instruction": (
        "Prompt tập trung vào điều không được làm thay vì hướng dẫn tích cực AI phải làm gì."
    ),
    "Missing Grounding": (
        "Task phân tích tài liệu/dữ liệu nhưng không yêu cầu AI trích dẫn hoặc bám vào bằng chứng."
    ),
    "No Self-check": "Prompt không yêu cầu AI tự kiểm tra kết quả trước khi trả lời.",
    "Long Context Ordering": (
        "Prompt có input dài/tài liệu dài nhưng đặt câu hỏi hoặc instruction ở vị trí dễ gây nhiễu."
    ),
    "Ambiguous Scope": (
        "Prompt thiếu phạm vi, tiêu chí hoàn thành, constraint, hoặc boundary nên AI dễ suy diễn sai."
    ),
    "Tool Or Environment Missing": (
        "Prompt thiếu thông tin về tool, môi trường chạy, framework, file/schema, hoặc dữ liệu đầu vào."
    ),
    "Insufficient Lesson Data": (
        "Bài học người dùng và bài học AI đều thiếu hoặc quá mơ hồ để suy ra lỗi prompt đáng tin cậy."
    ),
}

SDLC_TAXONOMY: dict[str, str] = {
    "Planning / Requirements": "Clarifying goals, requirements, acceptance criteria, scope, or user needs.",
    "Design / Architecture": "System design, data model design, API design, architecture, UX flow design.",
    "Development / Implementation": "Writing new code or implementing a feature.",
    "Testing / QA": "Creating, running, or improving tests; manual QA; validation.",
    "Debugging / Bug Fix": "Investigating or fixing bugs, errors, regressions, or broken behavior.",
    "Refactoring / Code Quality": "Cleanup, refactor, simplification, style, maintainability, performance tuning.",
    "Deployment / Release": "Build, packaging, release, CI/CD deployment, migration rollout.",
    "Operations / Maintenance": "Monitoring, support, environment maintenance, dependency updates, ops tasks.",
    "Documentation": "Writing or improving docs, comments, guides, summaries, specs.",
    "Project Management / Collaboration": "Planning work, reporting status, coordinating tasks, reviews.",
    "Research / Learning": "Exploration, technical research, comparing options, learning a tool or concept.",
    "Other": "Use only when no listed SDLC category fits.",
}


# Styling
HEADER_FILL = PatternFill("solid", start_color="1F4E78")
HEADER_FONT = Font(name="Arial", bold=True, color="FFFFFF", size=11)
TITLE_FONT = Font(name="Arial", bold=True, size=14, color="1F4E78")
SUBTITLE_FONT = Font(name="Arial", italic=True, size=10, color="595959")
CELL_FONT = Font(name="Arial", size=10)
NUMBER_FONT = Font(name="Arial", size=10, bold=True, color="1F4E78")
TOTAL_FILL = PatternFill("solid", start_color="D9E1F2")
SECTION_FILL = PatternFill("solid", start_color="DDEBF7")
THIN = Side(border_style="thin", color="BFBFBF")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT = Alignment(horizontal="left", vertical="center", wrap_text=True)

PROFESSIONAL_NAVY = "17365D"
PROFESSIONAL_BLUE = "1F4E78"
PROFESSIONAL_TEAL = "00A6A6"
PROFESSIONAL_ORANGE = "ED7D31"
PROFESSIONAL_LIGHT_BLUE = "DDEBF7"
PROFESSIONAL_ALT_FILL = PatternFill("solid", start_color="F7FBFF")
PROFESSIONAL_HEADER_FILL = PatternFill("solid", start_color=PROFESSIONAL_NAVY)
PROFESSIONAL_SECTION_FILL = PatternFill("solid", start_color=PROFESSIONAL_LIGHT_BLUE)
PROFESSIONAL_HEADER_FONT = Font(name="Aptos", bold=True, color="FFFFFF", size=11)
PROFESSIONAL_TITLE_FONT = Font(name="Aptos Display", bold=True, size=16, color=PROFESSIONAL_NAVY)
PROFESSIONAL_SUBTITLE_FONT = Font(name="Aptos", italic=True, size=10, color="666666")
PROFESSIONAL_BODY_FONT = Font(name="Aptos", size=10, color="1F1F1F")


# --------------------------------------------------------------------------- #
# Data model
# --------------------------------------------------------------------------- #


@dataclass
class ReportSession:
    row_id: str
    staff: str
    date: str
    title: str
    tool: str
    category: str
    task_desc: str
    rating: float | None
    est_hours: float | None
    actual_hours: float | None
    time_saved: float | None
    user_lesson: str
    tags: str
    source_file: str
    prompt: str = ""
    result: str = ""
    ai_lesson: str = ""
    error_labels: list[str] = field(default_factory=list)
    error_evidence: str = ""
    sdlc_category: str = "Other"
    sdlc_confidence: float | None = None
    sdlc_reason: str = ""

    @property
    def cache_hash(self) -> str:
        payload = {
            "version": PROMPT_VERSION,
            "staff": self.staff,
            "date": self.date,
            "title": self.title,
            "tool": self.tool,
            "category": self.category,
            "task_desc": self.task_desc,
            "prompt": self.prompt,
            "result": self.result,
            "user_lesson": self.user_lesson,
            "ai_lesson": self.ai_lesson,
        }
        raw = json.dumps(payload, ensure_ascii=False, sort_keys=True)
        return hashlib.sha1(raw.encode("utf-8")).hexdigest()

    @property
    def saved_hours(self) -> float | None:
        if self.time_saved is not None:
            return self.time_saved
        if self.est_hours is not None and self.actual_hours is not None:
            return self.est_hours - self.actual_hours
        return None


# --------------------------------------------------------------------------- #
# Workbook parsing helpers
# --------------------------------------------------------------------------- #


def _norm_header(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "").strip())


def _find_header_row(ws, must_contain: str = "Staff", max_scan: int = 25) -> int:
    for row_idx in range(1, min(ws.max_row, max_scan) + 1):
        headers = {_norm_header(ws.cell(row=row_idx, column=col).value) for col in range(1, ws.max_column + 1)}
        if must_contain in headers:
            return row_idx
    raise ValueError(f"Could not find a header row containing {must_contain!r} in sheet {ws.title!r}")


def _header_map(ws, header_row: int) -> dict[str, int]:
    mapping: dict[str, int] = {}
    for col in range(1, ws.max_column + 1):
        header = _norm_header(ws.cell(row=header_row, column=col).value)
        if header:
            mapping[header] = col
    return mapping


def _value(ws, row: int, headers: dict[str, int], *names: str) -> Any:
    for name in names:
        col = headers.get(name)
        if col is not None:
            value = ws.cell(row=row, column=col).value
            if isinstance(value, str):
                value = value.strip()
            return value
    return None


def _to_float(value: Any) -> float | None:
    if value is None or value == "":
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value).strip().replace(",", ".")
    match = re.search(r"-?\d+(?:\.\d+)?", text)
    if not match:
        return None
    try:
        return float(match.group(0))
    except ValueError:
        return None


def _fmt_date(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.strftime("%d/%m/%Y")
    return str(value).strip()


def _session_key(staff: str, date: str, title: str, tool: str) -> tuple[str, str, str, str]:
    return (
        staff.strip().casefold(),
        date.strip().casefold(),
        title.strip().casefold(),
        tool.strip().casefold(),
    )


def read_sessions(wb) -> list[ReportSession]:
    if RAW_LOG_SHEET not in wb.sheetnames:
        raise ValueError(f"Input workbook must contain {RAW_LOG_SHEET!r}; is this the output of report.py?")

    raw_ws = wb[RAW_LOG_SHEET]
    raw_header_row = _find_header_row(raw_ws)
    raw_headers = _header_map(raw_ws, raw_header_row)

    required = ["Staff", "Ngày", "Tên Phiên", "Công Cụ", "Mô Tả", "Rating", "EST (h)", "Actual (h)"]
    missing = [header for header in required if header not in raw_headers]
    if missing:
        raise ValueError(
            "The report workbook is missing current Raw Log columns required for charts: "
            + ", ".join(missing)
            + ". Regenerate it with the current report.py first."
        )

    sessions: list[ReportSession] = []
    for row in range(raw_header_row + 1, raw_ws.max_row + 1):
        staff = str(_value(raw_ws, row, raw_headers, "Staff") or "").strip()
        title = str(_value(raw_ws, row, raw_headers, "Tên Phiên") or "").strip()
        tool = str(_value(raw_ws, row, raw_headers, "Công Cụ") or "").strip()
        if not staff and not title and not tool:
            continue
        sessions.append(
            ReportSession(
                row_id=f"S{len(sessions) + 1}",
                staff=staff or "(không rõ)",
                date=_fmt_date(_value(raw_ws, row, raw_headers, "Ngày")),
                title=title,
                tool=tool or "(không rõ)",
                category=str(_value(raw_ws, row, raw_headers, "Danh Mục") or "").strip(),
                task_desc=str(_value(raw_ws, row, raw_headers, "Mô Tả") or "").strip(),
                rating=_to_float(_value(raw_ws, row, raw_headers, "Rating")),
                est_hours=_to_float(_value(raw_ws, row, raw_headers, "EST (h)")),
                actual_hours=_to_float(_value(raw_ws, row, raw_headers, "Actual (h)")),
                time_saved=_to_float(_value(raw_ws, row, raw_headers, "Tiết Kiệm (h)", "Giờ Tiết Kiệm")),
                user_lesson=str(_value(raw_ws, row, raw_headers, "Bài Học Người Dùng") or "").strip(),
                tags=str(_value(raw_ws, row, raw_headers, "Tags") or "").strip(),
                source_file=str(_value(raw_ws, row, raw_headers, "Source File") or "").strip(),
            )
        )

    if not sessions:
        raise ValueError(f"No sessions found in {RAW_LOG_SHEET!r}")

    enrich_sessions_from_ai_sheet(wb, sessions)
    return sessions


def enrich_sessions_from_ai_sheet(wb, sessions: list[ReportSession]) -> None:
    if AI_COMPARE_SHEET not in wb.sheetnames:
        return

    ai_ws = wb[AI_COMPARE_SHEET]
    header_row = _find_header_row(ai_ws)
    headers = _header_map(ai_ws, header_row)

    by_key: dict[tuple[str, str, str, str], dict[str, str]] = {}
    ordered: list[dict[str, str]] = []
    for row in range(header_row + 1, ai_ws.max_row + 1):
        staff = str(_value(ai_ws, row, headers, "Staff") or "").strip()
        title = str(_value(ai_ws, row, headers, "Tên Phiên") or "").strip()
        tool = str(_value(ai_ws, row, headers, "Công Cụ") or "").strip()
        if not staff and not title and not tool:
            continue

        data = {
            "staff": staff,
            "date": _fmt_date(_value(ai_ws, row, headers, "Ngày")),
            "title": title,
            "tool": tool,
            "task_desc": str(_value(ai_ws, row, headers, "Mô Tả Nhiệm Vụ") or "").strip(),
            "prompt": str(_value(ai_ws, row, headers, "Prompt Chính") or "").strip(),
            "result": str(_value(ai_ws, row, headers, "Kết Quả") or "").strip(),
            "user_lesson": str(_value(ai_ws, row, headers, "Bài Học Người Dùng") or "").strip(),
            "ai_lesson": str(_value(ai_ws, row, headers, "Bài Học AI Suy Luận") or "").strip(),
        }
        ordered.append(data)
        by_key[_session_key(data["staff"], data["date"], data["title"], data["tool"])] = data

    for idx, session in enumerate(sessions):
        data = by_key.get(_session_key(session.staff, session.date, session.title, session.tool))
        if data is None and idx < len(ordered):
            data = ordered[idx]
        if not data:
            continue
        session.task_desc = session.task_desc or data.get("task_desc", "")
        session.prompt = data.get("prompt", "")
        session.result = data.get("result", "")
        session.user_lesson = session.user_lesson or data.get("user_lesson", "")
        session.ai_lesson = data.get("ai_lesson", "")


# --------------------------------------------------------------------------- #
# AI classification
# --------------------------------------------------------------------------- #


def _load_cache(cache_path: Path) -> dict[str, dict[str, Any]]:
    if not cache_path.exists():
        return {}
    try:
        raw = json.loads(cache_path.read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            return raw
    except Exception:
        pass
    return {}


def _save_cache(cache_path: Path, cache: dict[str, dict[str, Any]]) -> None:
    try:
        cache_path.write_text(json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8")
    except Exception as exc:
        print(f"  ⚠  Could not write cache {cache_path}: {exc}", file=sys.stderr)


def _truncate(value: str, limit: int = 1100) -> str:
    return value if len(value) <= limit else value[:limit] + "…"


def _json_dumps(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def build_classifier_prompt(
    sessions: list[ReportSession],
    error_taxonomy: dict[str, str],
) -> str:
    """Prompt follows Claude best practices: role, context, examples, XML tags, and JSON schema."""
    session_payload = [
        {
            "id": s.row_id,
            "staff": s.staff,
            "date": s.date,
            "title": _truncate(s.title, 220),
            "tool": s.tool,
            "category": s.category,
            "task_description": _truncate(s.task_desc),
            "user_prompt": _truncate(s.prompt),
            "ai_result": _truncate(s.result),
            "user_lesson": _truncate(s.user_lesson, 700) or "(trống)",
            "ai_inferred_lesson": _truncate(s.ai_lesson, 900) or "(trống)",
        }
        for s in sessions
    ]

    # The long variable input is placed before the operational instructions,
    # matching Anthropic's long-context ordering guidance.
    return f"""<role>
Bạn là chuyên gia prompt engineering và phân tích quy trình phát triển phần mềm.
Bạn phân loại nhật ký dùng AI của developer để tạo chart quản trị: lỗi prompt thường gặp và loại công việc theo SDLC.
</role>

<context>
Input là các phiên làm việc từ AI Dev Journal. Mỗi phiên có bài học người dùng tự ghi và bài học AI suy luận.
Mục tiêu là phân loại chính xác lỗi mà từng người dùng gặp phải, ưu tiên taxonomy cố định, chỉ tạo nhãn mới khi không có nhãn hiện tại nào phù hợp.
Các lỗi prompt phải dựa trên Claude Prompting Best Practices: rõ ràng/trực tiếp, thêm context, ví dụ few-shot, cấu trúc XML, role assignment, long-context ordering, positive instructions, grounding bằng quote, self-check, và output format rõ ràng.
</context>

<fixed_error_taxonomy>
{_json_dumps(error_taxonomy)}
</fixed_error_taxonomy>

<fixed_sdlc_taxonomy>
{_json_dumps(SDLC_TAXONOMY)}
</fixed_sdlc_taxonomy>

<journal_sessions>
{_json_dumps(session_payload)}
</journal_sessions>

<examples>
  <example>
    <input>
      {{"id":"S_EXAMPLE","task_description":"Nhờ AI sửa format bảng Excel nhưng output sai cột","user_lesson":"Cần nói rõ format mong muốn","ai_inferred_lesson":"Prompt thiếu schema output và constraint về cột"}}
    </input>
    <output>
      {{"id":"S_EXAMPLE","error_labels":["Clear and Format"],"new_error_labels":[],"error_evidence":"Cả user_lesson và ai_inferred_lesson đều nói thiếu format/schema output.","sdlc_category":"Development / Implementation","sdlc_confidence":0.82,"sdlc_reason":"Task yêu cầu AI sửa format trong file/script hiện có."}}
    </output>
  </example>
</examples>

<instructions>
Thực hiện chính xác các bước sau:
1. Với mỗi session trong <journal_sessions>, đọc task_description, user_prompt, ai_result, user_lesson, và ai_inferred_lesson.
2. Gán 1 đến {MAX_LABELS_PER_SESSION} `error_labels` cho lỗi prompt mà người dùng gặp phải:
   - Ưu tiên chọn nhãn trong <fixed_error_taxonomy>.
   - Chỉ thêm nhãn mới nếu không có nhãn cố định nào mô tả đúng lỗi chính.
   - Nhãn mới phải ngắn, Title Case, 2-5 từ, không trùng ý nghĩa với nhãn đã có.
   - Nếu bài học không đủ dữ liệu, dùng "Insufficient Lesson Data".
3. Gán chính xác một `sdlc_category` từ <fixed_sdlc_taxonomy> cho task của session.
4. Viết `error_evidence` và `sdlc_reason` ngắn gọn bằng tiếng Việt, dựa trên bằng chứng trong input; không suy diễn quá dữ liệu.
5. Trả về kết quả cho mọi session, giữ nguyên `id`.
</instructions>

<output_format>
Trả về DUY NHẤT một JSON object hợp lệ, không markdown:
{{
  "sessions": [
    {{
      "id": "S1",
      "error_labels": ["Clear and Format"],
      "new_error_labels": [],
      "error_evidence": "Lý do ngắn bằng tiếng Việt",
      "sdlc_category": "Development / Implementation",
      "sdlc_confidence": 0.0,
      "sdlc_reason": "Lý do ngắn bằng tiếng Việt"
    }}
  ],
  "new_taxonomy": [
    {{"label": "New Label", "definition": "Định nghĩa ngắn"}}
  ]
}}
</output_format>

Trước khi trả lời, hãy tự kiểm tra:
- Mỗi session input đều có đúng một object output.
- Mọi `sdlc_category` nằm trong fixed_sdlc_taxonomy.
- `error_labels` có tối đa {MAX_LABELS_PER_SESSION} nhãn, ưu tiên nhãn cố định, và nhãn mới chỉ xuất hiện khi thật sự cần.
- JSON hợp lệ và không có giải thích ngoài JSON.
"""


def _call_openai(model: str, prompt: str, timeout: int = 300) -> str:
    base = (OPENAI_BASE_URL or "").rstrip("/")
    if not base:
        raise RuntimeError("OPENAI_BASE_URL is required unless --no-ai is used")

    is_azure = "cognitiveservices.azure.com" in base or "openai.azure.com" in base
    endpoints: list[tuple[str, dict[str, str], bool]] = []
    if is_azure:
        host = re.sub(r"/openai(/v1)?$", "", base).rstrip("/")
        # Keep report.py-compatible Azure deployment routing first.
        endpoints.append((
            f"{host}/openai/deployments/{model}/chat/completions?api-version=2024-12-01-preview",
            {"api-key": OPENAI_API_KEY or ""},
            False,
        ))
        # Some Azure/OpenAI-compatible gateways expose the v1 route directly
        # even when their hostname contains "cognitiveservices.azure.com".
        endpoints.append((
            f"{base}/chat/completions",
            {"api-key": OPENAI_API_KEY or ""},
            True,
        ))
    else:
        headers = {}
        if OPENAI_API_KEY:
            headers["Authorization"] = f"Bearer {OPENAI_API_KEY}"
        endpoints.append((f"{base}/chat/completions", headers, True))

    body_template: dict[str, Any] = {
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.1,
        "max_completion_tokens": 4096,
        "response_format": {"type": "json_object"},
    }

    last_error: requests.RequestException | None = None
    for url, headers, include_model in endpoints:
        body = dict(body_template)
        if include_model:
            body["model"] = model

        variants: list[dict[str, Any]] = [body]

        no_response_format = dict(body)
        no_response_format.pop("response_format", None)
        variants.append(no_response_format)

        max_tokens_body = dict(no_response_format)
        max_tokens_body["max_tokens"] = max_tokens_body.pop("max_completion_tokens")
        variants.append(max_tokens_body)

        for candidate in variants:
            try:
                response = requests.post(url, headers=headers, json=candidate, timeout=timeout)
                response.raise_for_status()
                return response.json()["choices"][0]["message"]["content"]
            except requests.HTTPError as exc:
                last_error = exc
                status = exc.response.status_code if exc.response is not None else None
                # Retry alternate body shapes and, for Azure-like hosts, alternate
                # OpenAI-compatible routing on common schema/routing failures.
                if status not in {400, 404, 422}:
                    raise
            except requests.RequestException as exc:
                last_error = exc
                raise
    assert last_error is not None
    raise last_error


def _parse_json_object(raw: str) -> dict[str, Any]:
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", (raw or "").strip(), flags=re.MULTILINE)
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        raise ValueError("Model response did not contain a JSON object")
    parsed = json.loads(match.group(0))
    if not isinstance(parsed, dict):
        raise ValueError("Model response JSON root was not an object")
    return parsed


def _coerce_labels(raw: Any, taxonomy: dict[str, str]) -> list[str]:
    if isinstance(raw, str):
        values = [part.strip() for part in re.split(r"[,;|]", raw)]
    elif isinstance(raw, list):
        values = [str(item).strip() for item in raw]
    else:
        values = []

    labels: list[str] = []
    known_casefold = {label.casefold(): label for label in taxonomy}
    for value in values:
        if not value:
            continue
        label = known_casefold.get(value.casefold(), value)
        if label not in labels:
            labels.append(label)
        if len(labels) >= MAX_LABELS_PER_SESSION:
            break
    return labels or ["Insufficient Lesson Data"]


def classify_sessions(
    sessions: list[ReportSession],
    model: str,
    cache_path: Path,
    batch_size: int,
    timeout: int,
) -> None:
    cache = _load_cache(cache_path)
    taxonomy = dict(ERROR_TAXONOMY)

    misses: list[ReportSession] = []
    hits = 0
    for session in sessions:
        key = f"{model}:{session.cache_hash}"
        cached = cache.get(key)
        if cached:
            session.error_labels = list(cached.get("error_labels") or ["Insufficient Lesson Data"])
            session.error_evidence = str(cached.get("error_evidence") or "")
            session.sdlc_category = str(cached.get("sdlc_category") or "Other")
            session.sdlc_confidence = _to_float(cached.get("sdlc_confidence"))
            session.sdlc_reason = str(cached.get("sdlc_reason") or "")
            hits += 1
            continue
        misses.append(session)

    print(f"🤖  Classifying errors + SDLC with {model}. Cache hits: {hits}/{len(sessions)}")

    for start in range(0, len(misses), batch_size):
        batch = misses[start:start + batch_size]
        print(f"  • Batch {start // batch_size + 1}: {len(batch)} session(s)")
        prompt = build_classifier_prompt(batch, taxonomy)
        raw = _call_openai(model=model, prompt=prompt, timeout=timeout)
        parsed = _parse_json_object(raw)

        for item in parsed.get("new_taxonomy", []) if isinstance(parsed.get("new_taxonomy"), list) else []:
            if not isinstance(item, dict):
                continue
            label = str(item.get("label") or "").strip()
            definition = str(item.get("definition") or "").strip()
            if label and label not in taxonomy:
                taxonomy[label] = definition or "Model-added prompt error label."

        by_id: dict[str, dict[str, Any]] = {}
        result_sessions = parsed.get("sessions")
        if isinstance(result_sessions, list):
            by_id = {
                str(item.get("id") or ""): item
                for item in result_sessions
                if isinstance(item, dict) and item.get("id")
            }

        for session in batch:
            item = by_id.get(session.row_id, {})
            for new_label in item.get("new_error_labels", []) if isinstance(item.get("new_error_labels"), list) else []:
                new_label_text = str(new_label).strip()
                if new_label_text and new_label_text not in taxonomy:
                    taxonomy[new_label_text] = "Model-added prompt error label."

            session.error_labels = _coerce_labels(item.get("error_labels"), taxonomy)
            session.error_evidence = str(item.get("error_evidence") or "").strip()
            sdlc_category = str(item.get("sdlc_category") or "Other").strip()
            if sdlc_category not in SDLC_TAXONOMY:
                sdlc_category = "Other"
            session.sdlc_category = sdlc_category
            session.sdlc_confidence = _to_float(item.get("sdlc_confidence"))
            session.sdlc_reason = str(item.get("sdlc_reason") or "").strip()

            cache[f"{model}:{session.cache_hash}"] = {
                "error_labels": session.error_labels,
                "error_evidence": session.error_evidence,
                "sdlc_category": session.sdlc_category,
                "sdlc_confidence": session.sdlc_confidence,
                "sdlc_reason": session.sdlc_reason,
            }
        _save_cache(cache_path, cache)

    print(f"✔  Classification complete. Cache: {cache_path}")


def mark_unclassified(sessions: list[ReportSession]) -> None:
    for session in sessions:
        session.error_labels = ["Unclassified"]
        session.error_evidence = "AI classification skipped (--no-ai)."
        session.sdlc_category = "Other"
        session.sdlc_confidence = None
        session.sdlc_reason = "AI classification skipped (--no-ai)."


# --------------------------------------------------------------------------- #
# Aggregation
# --------------------------------------------------------------------------- #


def _sum_float(values: list[float | None]) -> float:
    return round(sum(value or 0 for value in values), 2)


def aggregate_sessions(items: list[ReportSession]) -> dict[str, float | int]:
    est = _sum_float([s.est_hours for s in items])
    actual = _sum_float([s.actual_hours for s in items])
    saved = _sum_float([s.saved_hours for s in items])
    efficiency = round(saved / est * 100, 2) if est else 0
    return {
        "sessions": len(items),
        "est": est,
        "actual": actual,
        "saved": saved,
        "efficiency": efficiency,
    }


def group_aggregate(sessions: list[ReportSession], attr: str) -> list[tuple[str, dict[str, float | int]]]:
    groups: dict[str, list[ReportSession]] = defaultdict(list)
    for session in sessions:
        key = getattr(session, attr) or "(none)"
        groups[str(key)].append(session)
    rows = [(key, aggregate_sessions(items)) for key, items in groups.items()]
    rows.sort(key=lambda row: (-float(row[1]["saved"]), row[0]))
    return rows


def date_aggregate(sessions: list[ReportSession]) -> list[tuple[str, dict[str, float | int]]]:
    rows = group_aggregate(sessions, "date")

    def sort_key(row: tuple[str, dict[str, float | int]]) -> tuple[datetime, str]:
        value = row[0]
        for fmt in ("%d/%m/%Y", "%Y-%m-%d %H:%M:%S", "%Y-%m-%d"):
            try:
                return datetime.strptime(value, fmt), value
            except ValueError:
                pass
        return datetime.max, value

    return sorted(rows, key=sort_key)


def rating_counts_by_tool(sessions: list[ReportSession]) -> list[list[Any]]:
    tools = sorted({s.tool or "(không rõ)" for s in sessions})
    rows: list[list[Any]] = []
    for tool in tools:
        items = [s for s in sessions if (s.tool or "(không rõ)") == tool]
        counts = Counter()
        ratings: list[float] = []
        for session in items:
            if session.rating is None:
                continue
            rounded = int(round(session.rating))
            if 1 <= rounded <= 5:
                counts[rounded] += 1
                ratings.append(session.rating)
        total = sum(counts.values())
        avg = round(sum(ratings) / len(ratings), 2) if ratings else 0
        rows.append([tool, counts[1], counts[2], counts[3], counts[4], counts[5], total, avg])
    rows.sort(key=lambda row: (-row[6], row[0]))
    return rows


def collapsed_error_labels(sessions: list[ReportSession]) -> tuple[list[str], Counter[str]]:
    raw_counts: Counter[str] = Counter()
    for session in sessions:
        labels = session.error_labels or ["Unclassified"]
        for label in labels:
            raw_counts[label] += 1

    top = [label for label, _ in raw_counts.most_common(MAX_ERROR_LABELS_FOR_CHART)]
    collapsed: Counter[str] = Counter()
    for label, count in raw_counts.items():
        collapsed[label if label in top else "Other"] += count

    labels = [label for label in top if label in collapsed]
    if collapsed.get("Other"):
        labels.append("Other")
    return labels, collapsed


def error_staff_matrix(sessions: list[ReportSession], labels: list[str]) -> tuple[list[str], list[list[Any]]]:
    staff_list = sorted({s.staff for s in sessions})
    rows: list[list[Any]] = []
    top_set = set(labels) - {"Other"}
    for label in labels:
        row: list[Any] = [label]
        for staff in staff_list:
            count = 0
            for session in sessions:
                if session.staff != staff:
                    continue
                session_labels = session.error_labels or ["Unclassified"]
                if label == "Other":
                    count += sum(1 for item in session_labels if item not in top_set)
                elif label in session_labels:
                    count += 1
            row.append(count)
        rows.append(row)
    return staff_list, rows


def sdlc_staff_matrix(sessions: list[ReportSession]) -> tuple[list[str], list[list[Any]]]:
    staff_list = sorted({s.staff for s in sessions})
    rows: list[list[Any]] = []
    for category in SDLC_TAXONOMY:
        row: list[Any] = [category]
        for staff in staff_list:
            row.append(sum(1 for s in sessions if s.staff == staff and s.sdlc_category == category))
        rows.append(row)
    return staff_list, rows


def sdlc_task_chart_matrix(sessions: list[ReportSession]) -> tuple[list[str], list[list[Any]]]:
    task_counts_by_stage: dict[str, Counter[str]] = {category: Counter() for category in SDLC_TAXONOMY}
    for category in SDLC_TAXONOMY:
        stage_sessions = []
        for session in sessions:
            session_category = session.sdlc_category if session.sdlc_category in SDLC_TAXONOMY else "Other"
            if session_category == category:
                stage_sessions.append(session)
        stage_sessions.sort(key=lambda session: (session.title.casefold(), session.staff.casefold(), session.date))
        task_counts_by_stage[category].update(
            session.title or session.task_desc or "(unnamed task)"
            for session in stage_sessions
        )

    task_names: list[str] = []
    seen: set[str] = set()
    for category in SDLC_TAXONOMY:
        for task_name in task_counts_by_stage[category]:
            if task_name not in seen:
                seen.add(task_name)
                task_names.append(task_name)

    rows = [
        [category, *[task_counts_by_stage[category][task_name] for task_name in task_names]]
        for category in SDLC_TAXONOMY
    ]
    return task_names, rows


def sdlc_task_detail_rows(sessions: list[ReportSession]) -> list[list[Any]]:
    rows: list[list[Any]] = []
    for category in SDLC_TAXONOMY:
        stage_sessions = [
            session
            for session in sessions
            if (session.sdlc_category if session.sdlc_category in SDLC_TAXONOMY else "Other") == category
        ]
        stage_sessions.sort(key=lambda session: (session.title.casefold(), session.staff.casefold(), session.date))
        for session in stage_sessions:
            saved = session.saved_hours
            efficiency = round(saved / session.est_hours * 100, 2) if saved is not None and session.est_hours else 0
            rows.append([
                category,
                session.title or session.task_desc or "(unnamed task)",
                session.staff,
                session.date,
                session.est_hours or 0,
                session.actual_hours or 0,
                saved or 0,
                efficiency,
            ])
    return rows


# --------------------------------------------------------------------------- #
# Excel writing helpers
# --------------------------------------------------------------------------- #


def reset_generated_sheets(wb) -> None:
    for name in GENERATED_SHEETS:
        if name in wb.sheetnames:
            del wb[name]


def _set_widths(ws, widths: list[int]) -> None:
    for idx, width in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(idx)].width = width


def _style_range(ws, row1: int, row2: int, col1: int, col2: int, header_row: int | None = None) -> None:
    for row in ws.iter_rows(min_row=row1, max_row=row2, min_col=col1, max_col=col2):
        for cell in row:
            cell.border = BORDER
            cell.font = CELL_FONT
            cell.alignment = CENTER if isinstance(cell.value, (int, float)) else LEFT
    if header_row:
        for cell in ws.iter_rows(min_row=header_row, max_row=header_row, min_col=col1, max_col=col2).__next__():
            cell.fill = HEADER_FILL
            cell.font = HEADER_FONT
            cell.alignment = CENTER


def _title(ws, row: int, title: str, subtitle: str, n_cols: int) -> int:
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=n_cols)
    ws.cell(row=row, column=1, value=title).font = TITLE_FONT
    ws.cell(row=row, column=1).alignment = LEFT
    ws.merge_cells(start_row=row + 1, start_column=1, end_row=row + 1, end_column=n_cols)
    ws.cell(row=row + 1, column=1, value=subtitle).font = SUBTITLE_FONT
    ws.cell(row=row + 1, column=1).alignment = LEFT
    return row + 3


def _write_table(ws, start_row: int, start_col: int, headers: list[str], rows: list[list[Any]]) -> tuple[int, int]:
    for col_offset, header in enumerate(headers):
        ws.cell(row=start_row, column=start_col + col_offset, value=header)
    for row_offset, row in enumerate(rows, 1):
        for col_offset, value in enumerate(row):
            ws.cell(row=start_row + row_offset, column=start_col + col_offset, value=value)

    end_row = start_row + len(rows)
    end_col = start_col + len(headers) - 1
    _style_range(ws, start_row, end_row, start_col, end_col, header_row=start_row)
    return end_row, end_col


def _bar_chart(
    ws,
    title: str,
    min_row: int,
    max_row: int,
    min_col: int,
    max_col: int,
    category_col: int,
    anchor: str,
    y_title: str = "Value",
    stacked: bool = False,
    chart_type: str = "col",
    height: float = 9,
    width: float = 18,
) -> None:
    if max_row <= min_row:
        return
    chart = BarChart()
    chart.type = chart_type
    chart.style = 10
    chart.title = title
    chart.y_axis.title = y_title
    chart.x_axis.title = ws.cell(row=min_row, column=category_col).value
    if stacked:
        chart.grouping = "stacked"
        chart.overlap = 100
    data = Reference(ws, min_col=min_col, max_col=max_col, min_row=min_row, max_row=max_row)
    cats = Reference(ws, min_col=category_col, min_row=min_row + 1, max_row=max_row)
    chart.add_data(data, titles_from_data=True)
    chart.set_categories(cats)
    chart.height = height
    chart.width = width
    ws.add_chart(chart, anchor)


def _line_chart(
    ws,
    title: str,
    min_row: int,
    max_row: int,
    min_col: int,
    max_col: int,
    category_col: int,
    anchor: str,
    y_title: str = "Value",
) -> None:
    if max_row <= min_row:
        return
    chart = LineChart()
    chart.style = 13
    chart.title = title
    chart.y_axis.title = y_title
    chart.x_axis.title = ws.cell(row=min_row, column=category_col).value
    data = Reference(ws, min_col=min_col, max_col=max_col, min_row=min_row, max_row=max_row)
    cats = Reference(ws, min_col=category_col, min_row=min_row + 1, max_row=max_row)
    chart.add_data(data, titles_from_data=True)
    chart.set_categories(cats)
    chart.height = 9
    chart.width = 18
    ws.add_chart(chart, anchor)


def _section_label(ws, row: int, text: str, n_cols: int = 6) -> int:
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=n_cols)
    cell = ws.cell(row=row, column=1, value=text)
    cell.fill = SECTION_FILL
    cell.font = Font(name="Arial", bold=True, size=12, color="1F4E78")
    cell.alignment = LEFT
    return row + 1


# --------------------------------------------------------------------------- #
# Sheet builders
# --------------------------------------------------------------------------- #


def build_efficiency_sheet(wb, sessions: list[ReportSession]) -> None:
    ws = wb.create_sheet(EFFICIENCY_SHEET)
    row = _title(
        ws,
        1,
        "📈 EST vs Actual — Time Saved",
        "Compare estimated hours without AI and actual hours with AI; Time Saved % = Saved / EST × 100.",
        7,
    )

    headers = ["Group", "Sessions", "EST (h)", "Actual (h)", "Saved (h)", "Time Saved %"]

    row = _section_label(ws, row, "Overall")
    overall = aggregate_sessions(sessions)
    overall_start = row
    overall_end, _ = _write_table(ws, row, 1, headers, [[
        "Overall",
        overall["sessions"],
        overall["est"],
        overall["actual"],
        overall["saved"],
        overall["efficiency"],
    ]])
    _bar_chart(ws, "Overall EST vs Actual", overall_start, overall_end, 3, 4, 1, "H4", y_title="Hours")
    row = overall_end + 3

    sections = [
        ("By Staff", group_aggregate(sessions, "staff"), "H20"),
        ("By Tool", group_aggregate(sessions, "tool"), "H36"),
        ("By Category", group_aggregate(sessions, "category"), "H52"),
    ]
    for label, data, anchor in sections:
        row = _section_label(ws, row, label)
        table_rows = [
            [key, agg["sessions"], agg["est"], agg["actual"], agg["saved"], agg["efficiency"]]
            for key, agg in data
        ]
        start = row
        end, _ = _write_table(ws, row, 1, headers, table_rows)
        _bar_chart(ws, f"{label}: EST vs Actual", start, end, 3, 4, 1, anchor, y_title="Hours")
        row = end + 3

    row = _section_label(ws, row, "Over Time")
    table_rows = [
        [key, agg["sessions"], agg["est"], agg["actual"], agg["saved"], agg["efficiency"]]
        for key, agg in date_aggregate(sessions)
    ]
    start = row
    end, _ = _write_table(ws, row, 1, headers, table_rows)
    _line_chart(ws, "Over Time: EST vs Actual", start, end, 3, 4, 1, "H68", y_title="Hours")

    _set_widths(ws, [24, 10, 12, 12, 12, 14, 4, 20, 20, 20])
    ws.freeze_panes = "A4"


def build_rating_sheet(wb, sessions: list[ReportSession]) -> None:
    ws = wb.create_sheet(RATING_SHEET)
    header_row = _title(
        ws,
        1,
        "⭐ User Satisfaction by Tool",
        "Count of 1★–5★ ratings per AI tool.",
        8,
    )
    headers = ["Tool", "1★", "2★", "3★", "4★", "5★", "Total Rated", "Avg Rating"]
    rows = rating_counts_by_tool(sessions)
    end_row, _ = _write_table(ws, header_row, 1, headers, rows)
    _bar_chart(ws, "Rating Counts per Tool", header_row, end_row, 2, 6, 1, "J4", y_title="Sessions", stacked=True)
    _set_widths(ws, [24, 8, 8, 8, 8, 8, 12, 12])
    ws.freeze_panes = "A4"


def build_error_data_sheet(wb, sessions: list[ReportSession]) -> None:
    ws = wb.create_sheet(ERROR_DATA_SHEET)
    row = _title(
        ws,
        1,
        "🏷️ Prompt Error Classification Data",
        "Multi-label error classification from user lesson + AI inferred lesson.",
        12,
    )

    headers = [
        "Staff",
        "Ngày",
        "Tên Phiên",
        "Công Cụ",
        "Danh Mục",
        "Mô Tả",
        "Bài Học Người Dùng",
        "Bài Học AI Suy Luận",
        "Error Labels",
        "Evidence",
        "Source File",
    ]
    rows = [
        [
            s.staff,
            s.date,
            s.title,
            s.tool,
            s.category,
            s.task_desc,
            s.user_lesson,
            s.ai_lesson,
            ", ".join(s.error_labels or ["Unclassified"]),
            s.error_evidence,
            s.source_file,
        ]
        for s in sessions
    ]
    _write_table(ws, row, 1, headers, rows)
    _set_widths(ws, [14, 12, 26, 16, 18, 38, 38, 42, 30, 42, 22])
    ws.freeze_panes = "A4"
    for row_idx in range(row + 1, row + 1 + len(rows)):
        ws.row_dimensions[row_idx].height = 70


def build_error_chart_sheet(wb, sessions: list[ReportSession]) -> None:
    ws = wb.create_sheet(ERROR_CHART_SHEET)
    row = _title(
        ws,
        1,
        "🏷️ Prompt Error Charts",
        f"Top {MAX_ERROR_LABELS_FOR_CHART} prompt error labels + Other; labels may be multi-label per session.",
        10,
    )

    labels, counts = collapsed_error_labels(sessions)

    row = _section_label(ws, row, "Top Error Labels", n_cols=4)
    top_start = row
    top_rows = [[label, counts[label]] for label in labels]
    top_end, _ = _write_table(ws, row, 1, ["Error Label", "Count"], top_rows)
    _bar_chart(ws, "Top Prompt Errors", top_start, top_end, 2, 2, 1, "E4", y_title="Occurrences")
    row = top_end + 3

    staff_list, matrix_rows = error_staff_matrix(sessions, labels)
    row = _section_label(ws, row, "Error Labels by Staff", n_cols=max(2, len(staff_list) + 1))
    matrix_start = row
    matrix_end, _ = _write_table(ws, row, 1, ["Error Label", *staff_list], matrix_rows)
    if staff_list:
        _bar_chart(
            ws,
            "Prompt Errors by Staff",
            matrix_start,
            matrix_end,
            2,
            len(staff_list) + 1,
            1,
            "E22",
            y_title="Occurrences",
            stacked=False,
        )

    _set_widths(ws, [28, 12, *([12] * len(staff_list))])
    ws.freeze_panes = "A4"


def build_sdlc_sheet(wb, sessions: list[ReportSession]) -> None:
    ws = wb.create_sheet(SDLC_SHEET, 0)
    row = _title(
        ws,
        1,
        "🧭 SDLC Task Summary",
        "Summary of task names in each Software Development Life Cycle stage; detailed per-session metadata is omitted.",
        8,
    )

    summary_counts = Counter(s.sdlc_category for s in sessions)
    total_sessions = len(sessions)
    sessions_by_stage = {
        category: [
            session
            for session in sessions
            if (session.sdlc_category if session.sdlc_category in SDLC_TAXONOMY else "Other") == category
        ]
        for category in SDLC_TAXONOMY
    }

    row = _section_label(ws, row, "Tasks and Efficiency by SDLC Stage", n_cols=8)
    task_names_by_stage: dict[str, Counter[str]] = {category: Counter() for category in SDLC_TAXONOMY}
    for session in sessions:
        category = session.sdlc_category if session.sdlc_category in SDLC_TAXONOMY else "Other"
        task_name = session.title or session.task_desc or "(unnamed task)"
        task_names_by_stage.setdefault(category, Counter())[task_name] += 1

    def _format_task_names(category: str) -> str:
        task_counts = task_names_by_stage.get(category, Counter())
        if not task_counts:
            return "—"
        bullets = []
        for task_name, count in task_counts.items():
            suffix = f" (×{count})" if count > 1 else ""
            bullets.append(f"• {task_name}{suffix}")
        return "\n".join(bullets)

    summary_rows = []
    for category in SDLC_TAXONOMY:
        aggregate = aggregate_sessions(sessions_by_stage[category])
        summary_rows.append([
            category,
            _format_task_names(category),
            summary_counts[category],
            round(summary_counts[category] / total_sessions * 100, 1) if total_sessions else 0,
            aggregate["est"],
            aggregate["actual"],
            aggregate["saved"],
            aggregate["efficiency"],
        ])
    summary_start = row
    summary_end, _ = _write_table(
        ws,
        row,
        1,
        ["SDLC Stage", "Task Names", "Task Count", "Share %", "EST (h)", "Actual (h)", "Saved (h)", "Efficiency %"],
        summary_rows,
    )
    _bar_chart(ws, "Tasks by SDLC Stage", summary_start, summary_end, 3, 3, 1, "F4", y_title="Tasks")
    _bar_chart(
        ws,
        "Efficiency % by SDLC Stage",
        summary_start,
        summary_end,
        8,
        8,
        1,
        "O4",
        y_title="Efficiency %",
        chart_type="bar",
        height=10,
        width=18,
    )

    staff_list, matrix_rows = sdlc_staff_matrix(sessions)
    matrix_row = summary_end + 3
    matrix_row = _section_label(ws, matrix_row, "Task Count by SDLC Stage and Staff", n_cols=max(2, len(staff_list) + 1))
    matrix_start = matrix_row
    matrix_end, _ = _write_table(ws, matrix_row, 1, ["SDLC Stage", *staff_list], matrix_rows)
    if staff_list:
        _bar_chart(
            ws,
            "Tasks by SDLC Stage and Staff",
            matrix_start,
            matrix_end,
            2,
            len(staff_list) + 1,
            1,
            "F22",
            y_title="Tasks",
            stacked=True,
        )

    task_names, task_chart_rows = sdlc_task_chart_matrix(sessions)
    task_row = matrix_end + 3
    task_row = _section_label(ws, task_row, "All Tasks Within Each SDLC Stage", n_cols=max(5, len(task_names) + 1))
    task_start = task_row
    task_end, _ = _write_table(
        ws,
        task_row,
        1,
        ["SDLC Stage", *task_names],
        task_chart_rows,
    )
    _bar_chart(
        ws,
        "Tasks Within Each SDLC Stage",
        task_start,
        task_end,
        2,
        len(task_names) + 1,
        1,
        "F40",
        y_title="SDLC Stage",
        stacked=True,
        chart_type="bar",
        height=16,
        width=30,
    )

    detail_rows = sdlc_task_detail_rows(sessions)
    detail_row = task_end + 3
    detail_row = _section_label(ws, detail_row, "All Task Details by SDLC Stage", n_cols=8)
    detail_start = detail_row
    detail_end, _ = _write_table(
        ws,
        detail_row,
        1,
        ["SDLC Stage", "Task Name", "Staff", "Ngày", "EST (h)", "Actual (h)", "Saved (h)", "Efficiency %"],
        detail_rows,
    )

    widths = [30, *([18] * len(task_names))]
    if len(widths) >= 2:
        widths[1] = 46
    if len(widths) >= 3:
        widths[2] = max(widths[2], 16)
    if len(widths) >= 4:
        widths[3] = max(widths[3], 12)
    _set_widths(ws, widths)
    ws.freeze_panes = "A6"
    for row_idx in range(summary_start + 1, summary_end + 1):
        task_count = ws.cell(row=row_idx, column=3).value or 0
        ws.row_dimensions[row_idx].height = min(180, max(42, 18 * int(task_count)))
    for row_idx in range(task_start + 1, task_end + 1):
        ws.row_dimensions[row_idx].height = 28
    for row_idx in range(detail_start + 1, detail_end + 1):
        ws.row_dimensions[row_idx].height = 36


def _last_used_row(ws) -> int:
    for row in range(ws.max_row, 0, -1):
        if any(ws.cell(row=row, column=col).value not in (None, "") for col in range(1, ws.max_column + 1)):
            return row
    return 1


def _last_used_col(ws) -> int:
    for col in range(ws.max_column, 0, -1):
        if any(ws.cell(row=row, column=col).value not in (None, "") for row in range(1, ws.max_row + 1)):
            return col
    return 1


def _row_values(ws, row: int, max_col: int) -> list[str]:
    return [str(ws.cell(row=row, column=col).value or "").strip() for col in range(1, max_col + 1)]


def _looks_like_header(values: list[str]) -> bool:
    nonempty = [value for value in values if value]
    if len(nonempty) < 2:
        return False
    normalized = {value.casefold() for value in nonempty}
    header_markers = {
        "staff",
        "ngày",
        "tên phiên",
        "công cụ",
        "công cụ ai",
        "danh mục",
        "group",
        "sessions",
        "sdlc stage",
        "task name",
        "error label",
        "tool",
        "chỉ số",
        "giá trị",
        "rating",
    }
    return bool(normalized & header_markers)


def _iter_header_rows(ws) -> list[tuple[int, int]]:
    max_col = _last_used_col(ws)
    rows: list[tuple[int, int]] = []
    for row in range(1, min(_last_used_row(ws), 120) + 1):
        values = _row_values(ws, row, max_col)
        if _looks_like_header(values):
            header_width = max((idx for idx, value in enumerate(values, 1) if value), default=max_col)
            rows.append((row, header_width))
    return rows


def _contiguous_table_end(ws, header_row: int, max_col: int) -> int:
    row = header_row + 1
    while row <= ws.max_row:
        if not any(ws.cell(row=row, column=col).value not in (None, "") for col in range(1, max_col + 1)):
            return row - 1
        row += 1
    return ws.max_row


def _format_numeric_columns(ws, header_row: int, max_col: int, end_row: int) -> None:
    if end_row <= header_row:
        return
    for col in range(1, max_col + 1):
        header = str(ws.cell(row=header_row, column=col).value or "")
        header_cf = header.casefold()
        number_format: str | None = None
        if "%" in header or "tỷ lệ" in header_cf or "eff" in header_cf:
            number_format = "0.0"
        elif "(h)" in header_cf or "saved" in header_cf or "tiết kiệm" in header_cf or "actual" in header_cf or "est" in header_cf:
            number_format = "0.0"
        elif "rating" in header_cf or "★" in header:
            number_format = "0.0"
        elif "phiên" in header_cf or "sessions" in header_cf or "count" in header_cf:
            number_format = "0"

        if not number_format:
            continue
        for row in range(header_row + 1, end_row + 1):
            cell = ws.cell(row=row, column=col)
            if isinstance(cell.value, (int, float)):
                cell.number_format = number_format


def _add_color_scale(ws, header_row: int, max_col: int, end_row: int) -> None:
    if end_row <= header_row + 1:
        return
    for col in range(1, max_col + 1):
        header = str(ws.cell(row=header_row, column=col).value or "").casefold()
        if not any(marker in header for marker in ["%", "tỷ lệ", "eff", "rating", "saved", "tiết kiệm"]):
            continue
        if not any(isinstance(ws.cell(row=row, column=col).value, (int, float)) for row in range(header_row + 1, end_row + 1)):
            continue
        col_letter = get_column_letter(col)
        ws.conditional_formatting.add(
            f"{col_letter}{header_row + 1}:{col_letter}{end_row}",
            ColorScaleRule(
                start_type="min",
                start_color="F8696B",
                mid_type="percentile",
                mid_value=50,
                mid_color="FFEB84",
                end_type="max",
                end_color="63BE7B",
            ),
        )


def _shade_body_rows(ws, header_row: int, max_col: int, end_row: int) -> None:
    if end_row <= header_row:
        return
    # Avoid overwriting semantically colored long-form analysis sheets.
    if ws.title in {AI_COMPARE_SHEET, ERROR_DATA_SHEET}:
        return
    for row in range(header_row + 1, end_row + 1):
        if str(ws.cell(row=row, column=1).value or "").upper().startswith("TỔNG"):
            continue
        if (row - header_row) % 2 == 0:
            for col in range(1, max_col + 1):
                cell = ws.cell(row=row, column=col)
                if cell.fill.fill_type is None:
                    cell.fill = PROFESSIONAL_ALT_FILL


def _set_professional_filter(ws) -> None:
    filter_sheet_names = {
        "👤 Per Staff",
        "🔧 Per Tool",
        "📂 Per Category",
        "📅 Time Trend",
        "📝 Raw Log",
        AI_COMPARE_SHEET,
        ERROR_DATA_SHEET,
        RATING_SHEET,
    }
    if ws.title == SDLC_SHEET:
        for row in range(1, ws.max_row + 1):
            if ws.cell(row=row, column=1).value == "All Task Details by SDLC Stage":
                header_row = row + 1
                end_row = _contiguous_table_end(ws, header_row, 8)
                if end_row > header_row:
                    ws.auto_filter.ref = f"A{header_row}:H{end_row}"
                return
    if ws.title not in filter_sheet_names:
        return
    header_rows = _iter_header_rows(ws)
    if not header_rows:
        return
    header_row, max_col = header_rows[0]
    end_row = _contiguous_table_end(ws, header_row, max_col)
    if end_row > header_row:
        ws.auto_filter.ref = f"A{header_row}:{get_column_letter(max_col)}{end_row}"


def _polish_sheet(ws) -> None:
    max_row = _last_used_row(ws)
    max_col = _last_used_col(ws)
    ws.sheet_view.showGridLines = False
    ws.sheet_view.zoomScale = 90
    ws.freeze_panes = ws.freeze_panes or ("A5" if max_row >= 5 else None)

    if ws.cell(row=1, column=1).value:
        ws.cell(row=1, column=1).font = PROFESSIONAL_TITLE_FONT
        ws.row_dimensions[1].height = 24
    if ws.cell(row=2, column=1).value:
        ws.cell(row=2, column=1).font = PROFESSIONAL_SUBTITLE_FONT
        ws.row_dimensions[2].height = 20

    for row in ws.iter_rows(min_row=1, max_row=max_row, min_col=1, max_col=max_col):
        for cell in row:
            if cell.value in (None, ""):
                continue
            if not cell.font or not cell.font.bold:
                cell.font = PROFESSIONAL_BODY_FONT
            cell.alignment = CENTER if isinstance(cell.value, (int, float)) else LEFT

    for header_row, header_width in _iter_header_rows(ws):
        for cell in ws.iter_rows(min_row=header_row, max_row=header_row, min_col=1, max_col=header_width).__next__():
            cell.fill = PROFESSIONAL_HEADER_FILL
            cell.font = PROFESSIONAL_HEADER_FONT
            cell.alignment = CENTER
        end_row = _contiguous_table_end(ws, header_row, header_width)
        _format_numeric_columns(ws, header_row, header_width, end_row)
        _add_color_scale(ws, header_row, header_width, end_row)
        _shade_body_rows(ws, header_row, header_width, end_row)

    for row in range(1, max_row + 1):
        cell = ws.cell(row=row, column=1)
        if cell.value and len([v for v in _row_values(ws, row, max_col) if v]) == 1 and row not in {1, 2}:
            cell.fill = PROFESSIONAL_SECTION_FILL
            cell.font = Font(name="Aptos", bold=True, size=12, color=PROFESSIONAL_BLUE)

    _set_professional_filter(ws)
    ws.page_setup.orientation = "landscape" if max_col > 8 else "portrait"
    ws.page_setup.fitToWidth = 1
    ws.page_setup.fitToHeight = 0
    ws.sheet_properties.pageSetUpPr.fitToPage = True


def polish_workbook(wb) -> None:
    tab_colors = {
        SDLC_SHEET: PROFESSIONAL_TEAL,
        EFFICIENCY_SHEET: PROFESSIONAL_BLUE,
        RATING_SHEET: PROFESSIONAL_ORANGE,
        ERROR_CHART_SHEET: "C00000",
        ERROR_DATA_SHEET: "C00000",
        "📊 Tổng Quan": PROFESSIONAL_NAVY,
        "👤 Per Staff": PROFESSIONAL_BLUE,
        "🔧 Per Tool": "5B9BD5",
        "📂 Per Category": "70AD47",
        "📅 Time Trend": "8064A2",
        "📝 Raw Log": "7F7F7F",
        AI_COMPARE_SHEET: "FFC000",
    }
    for ws in wb.worksheets:
        ws.sheet_properties.tabColor = tab_colors.get(ws.title, PROFESSIONAL_NAVY)
        _polish_sheet(ws)


def build_chart_workbook(wb, sessions: list[ReportSession]) -> None:
    reset_generated_sheets(wb)
    build_sdlc_sheet(wb, sessions)
    build_efficiency_sheet(wb, sessions)
    build_rating_sheet(wb, sessions)
    build_error_data_sheet(wb, sessions)
    build_error_chart_sheet(wb, sessions)
    generated_front_order = [
        SDLC_SHEET,
        EFFICIENCY_SHEET,
        RATING_SHEET,
        ERROR_CHART_SHEET,
    ]
    for target_index, sheet_name in enumerate(generated_front_order):
        ws = wb[sheet_name]
        current_index = wb._sheets.index(ws)
        wb._sheets.insert(target_index, wb._sheets.pop(current_index))

    error_data_ws = wb[ERROR_DATA_SHEET]
    wb._sheets.append(wb._sheets.pop(wb._sheets.index(error_data_ws)))
    polish_workbook(wb)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def default_output_path(input_path: Path) -> Path:
    return input_path.with_name(f"{input_path.stem}_with_charts{input_path.suffix}")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create an enriched Excel workbook with charts from report.py output.",
    )
    parser.add_argument("report", type=Path, help="Input .xlsx workbook generated by report.py")
    parser.add_argument("-o", "--output", type=Path, help="Output enriched .xlsx workbook")
    parser.add_argument(
        "--model",
        default="qwen2.5:7b",
        help="OpenAI-compatible model for error + SDLC classification (default: qwen2.5:7b)",
    )
    parser.add_argument("--cache", type=Path, default=CACHE_PATH, help=f"AI classification cache (default: {CACHE_PATH})")
    parser.add_argument("--batch-size", type=int, default=20, help="Sessions per AI classification batch (default: 20)")
    parser.add_argument("--timeout", type=int, default=300, help="AI request timeout in seconds (default: 300)")
    parser.add_argument("--no-ai", action="store_true", help="Skip AI classification and mark rows as unclassified")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    input_path = args.report
    output_path = args.output or default_output_path(input_path)

    if not input_path.exists():
        print(f"Input workbook not found: {input_path}", file=sys.stderr)
        return 1
    if input_path.resolve() == output_path.resolve():
        print("Output path must be different from the input path so the original report remains unchanged.", file=sys.stderr)
        return 1
    if args.batch_size < 1:
        print("--batch-size must be >= 1", file=sys.stderr)
        return 1

    print(f"📂  Loading report workbook: {input_path}")
    wb = load_workbook(input_path)
    sessions = read_sessions(wb)
    print(f"✔  Parsed {len(sessions)} session(s) from {RAW_LOG_SHEET!r}")

    if args.no_ai:
        mark_unclassified(sessions)
        print("⏭  AI classification skipped (--no-ai)")
    else:
        try:
            classify_sessions(
                sessions=sessions,
                model=args.model,
                cache_path=args.cache,
                batch_size=args.batch_size,
                timeout=args.timeout,
            )
        except requests.HTTPError as exc:
            response = exc.response
            detail = ""
            if response is not None:
                detail = f" ({response.status_code} {response.reason})"
                body = response.text.strip()
                if body:
                    detail += f": {body[:500]}"
            print(f"AI classification failed{detail}", file=sys.stderr)
            print(
                "Check OPENAI_BASE_URL/OPENAI_API_KEY and --model, or run with --no-ai for chart-only output.",
                file=sys.stderr,
            )
            return 1
        except Exception as exc:
            print(f"AI classification failed: {exc}", file=sys.stderr)
            print(
                "Check OPENAI_BASE_URL/OPENAI_API_KEY and --model, or run with --no-ai for chart-only output.",
                file=sys.stderr,
            )
            return 1

    print("📊  Building chart sheets...")
    build_chart_workbook(wb, sessions)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(output_path)
    print(f"✔  Enriched workbook saved to: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
